import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar";
import SuperbaseProvider from "./providers/SuperbaseProvider";
import UserProvider from "./providers/UserProvider";
import ModelProvider from "./providers/ModelProvider";

const font = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotify Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <SuperbaseProvider>
          <UserProvider>
            <ModelProvider />
            <SideBar>{children}</SideBar>
          </UserProvider>
        </SuperbaseProvider>
      </body>
    </html>
  );
}
